server:
  port: 8081

# 白名单用户
check:
  whitelist:
    users: aaa,bbb,ccc,ddd,eee,fff

es-ibatis:
  address: jdbc:es://http://127.0.0.1:9200
  base-package: com.starter.common.lib.example.dao
  mappers: mapper/Student_Mapper.xml
